create table if not exists public.sky_articles (
  id text primary key,
  title text not null,
  blocks jsonb not null default '[]'::jsonb,
  info jsonb not null default '{}'::jsonb,
  author text not null default 'Sky Official',
  avatar text not null default 'S',
  main_version jsonb not null default '{"author":"Sky Official","votes":{"ok":10,"fail":0,"copy":0}}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.sky_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.sky_edit_proposals (
  id bigint generated by default as identity primary key,
  article_id text not null references public.sky_articles(id) on delete cascade,
  author text not null default 'Guest',
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.sky_articles enable row level security;
alter table public.sky_admins enable row level security;
alter table public.sky_edit_proposals enable row level security;

create or replace function public.is_sky_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.sky_admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_sky_admin() from public;
grant execute on function public.is_sky_admin() to authenticated;

drop policy if exists "Sky articles are public" on public.sky_articles;
create policy "Sky articles are public"
  on public.sky_articles for select
  to anon, authenticated
  using (true);

drop policy if exists "Sky admins manage articles" on public.sky_articles;
create policy "Sky admins manage articles"
  on public.sky_articles for all
  to authenticated
  using ((select public.is_sky_admin()))
  with check ((select public.is_sky_admin()));

drop policy if exists "Public can suggest edits" on public.sky_edit_proposals;
create policy "Public can suggest edits"
  on public.sky_edit_proposals for insert
  to anon, authenticated
  with check (length(trim(content)) > 0);

drop policy if exists "Sky admins review suggestions" on public.sky_edit_proposals;
create policy "Sky admins review suggestions"
  on public.sky_edit_proposals for select
  to authenticated
  using ((select public.is_sky_admin()));

grant select on public.sky_articles to anon, authenticated;
grant insert, update, delete on public.sky_articles to authenticated;
grant insert on public.sky_edit_proposals to anon, authenticated;
grant select on public.sky_edit_proposals to authenticated;

create or replace function public.sky_vote_block(
  p_article_id text,
  p_block_index integer,
  p_kind text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_kind not in ('ok', 'fail', 'copy') then
    raise exception 'Invalid vote kind';
  end if;
  if p_block_index < 0 then
    raise exception 'Invalid block index';
  end if;

  update public.sky_articles
  set blocks = jsonb_set(
    blocks,
    array[p_block_index::text, 'votes', p_kind],
    to_jsonb(coalesce((blocks -> p_block_index -> 'votes' ->> p_kind)::integer, 0) + 1),
    true
  )
  where id = p_article_id
    and p_block_index < jsonb_array_length(blocks);

  if not found then
    raise exception 'Article or block not found';
  end if;
end;
$$;

revoke all on function public.sky_vote_block(text, integer, text) from public;
grant execute on function public.sky_vote_block(text, integer, text) to anon, authenticated;

-- After creating your confirmed admin account in Authentication > Users, add its UUID:
-- insert into public.sky_admins (user_id) values ('PASTE_AUTH_USER_UUID_HERE');
